#!/bin/bash 
# 
if [ $# -gt 0 ]; then #si hay algun parametro 
	if [ $# -ne 1 -o $1 != "-h" ]; then #SI IGUAL QUE
		echo "Forma de uso: $0 [-h]" 
		exit 1 
	fi
  
	echo "Texto explicativo." 
	#exit 0 
	for i in * 
		do 
			lfn=`echo $i | gawk ' {str = tolower($0);print str }'` 
			if [ $lfn != $i ]; then 
				mv $i $lfn 
			fi 
		done 
else 
	echo "Forma de uso: $0 [-h]" 
	exit 1 
fi 
